DataDownload:
  save_path: './example_data/'
  start_time: '2020-08-01 00:00:00.00'
  end_time: '2020-08-02 00:00:00.00'
  channel_list: ["HH[ZNE]", "HH[Z21]", "BH[ZNE]","BH[Z21]","EH[ZNE]","EH[Z21]","SH[Z21]","SH[ZNE]","HN[ZNE]", "HN[Z23]"]
  exclude_network: ['SY']
  minlat: 34.0
  maxlat: 34.8
  minlon: -118.8
  maxlon: -118.0  
  client_list: ["SCEDC","IRIS","NCEDC"]
  sta_json_path: 'station_list.json'
  data_save_path: './example_data'

EqT:
  mseed_dir: 'example_data'
  sta_json_path: 'station_list.json'
  overlap: 0.3
  n_processor: 8
  det_res: detection_results
  model_path: '../../models/EqT/EqT_model.h5'
  gpuid: '0'
  number_of_sampling: 5
  EQ_threshold: 0.3
  P_threshold: 0.1
  S_threshold: 0.1
  txt_folder: ./EqTRes/
  STAXML: 'example_dataxml'

S_EqT:
  txt_folder: ./SEqTRes/
  P_branch_config: '../../S_EqT_codes/configs/P_branch.yaml'
  P_branch_model: '../../models/S_EqT/S_EqT_P_branch.hdf5'
  P_threshold: 0.1
  P_skip_threshold: 0.5
  keep_time_range_P: 6.0

  S_branch_config: '../../S_EqT_codes/configs/S_branch.yaml'
  S_branch_model: '../../models/S_EqT/S_EqT_S_branch.hdf5'
  S_threshold: 0.1
  S_skip_threshold: 0.5
  keep_time_range_S: 12.0

  max_search_distance: 99999
  exist_range: 20.0
  
REAL:
  ref_time: '2020-08-01'
  save_sta: 'sta_info_real_format.dat'
  year: ["\"2020\""]
  mon: ["\"08\""]
  day: ["\"01\""]
  R: "\"0.2/100/0.03/5/0.01\""
  G: "\"0.5/100/0.01/5\""
  V: "\"6.3/3.4/2.0/1.5/0\""
  S: "\"3/3/6/1/2.0/0/5.0/5.0\""
  eqt_dir: "./EqTRes/"
  seqt_dir: "./SEqTRes/"
  station: "\"./sta_info_real_format.dat\""
  ttime: "\"./REAL_scripts/tt_db/ttdb.txt\""

HypoInverse:
  save_sta: './Hypoinverse_scripts/HYPO_use.dat'
  save_pha_eqt: './Hypoinverse_scripts/HYPO_use_eqt.pha'
  save_pha_seqt: './Hypoinverse_scripts/HYPO_use_seqt.pha'
  eqt_event_dict: './catalogs/eqt_real_e_dict.npy'
  seqt_event_dict: './catalogs/seqt_real_e_dict.npy'
  HYPO_key: '20200801'
  lat_sign: 1.0
  lon_sign: -1.0

VIS:
  VIS_key: '20200801'

  profile_start_lat: 34.5
  profile_start_lon: -118.8
  profile_end_lat: 34.05
  profile_end_lon: -118.0

  MAXDEP: 40.0
  MINLAT: 34.0
  MAXLAT: 34.8
  MINLON: -118.8
  MAXLON: -118.0
  MAXERH: 5.0
  MAXERZ: 5.0
  MAXAZM: 180
  profile_range: 30.0